version: '3.7'

services:
  api: 
    container_name: api
    image: api_image
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - db

  db:
    container_name: db
    hostname: app_db
    image: library/postgres:14.1
    env_file:
      - .env
    ports:
      - "65432:5432"